html:
	scholdoc webpage-settings.yml index.md --citeproc --output=index.html
	scholdoc webpage-settings.yml 20Oct2015.md --citeproc --output=20Oct2015.html
	scholdoc webpage-settings.yml 26Oct2015.md --citeproc --output=26Oct2015.html

